pipeline {
    agent any
    stages {
        stage('Installing dependecies') {
            steps {
                sh 'python3 -m venv venv'
                sh 'venv/bin/pip install -r lab1/requirements.txt'
            }
        }
        stage('Creating dataset') {
            steps {
                sh 'venv/bin/python lab1/data_creation.py'
            }
        }
        stage('Preprocessing dataset') {
            steps {
                sh 'venv/bin/python lab1/data_preprocessing.py'
            }
        }
        stage('Training model') {
            steps {
                sh 'venv/bin/python lab1/model_preparation.py'
            }
        }
        stage('Testing model') {
            steps {
                sh 'venv/bin/python lab1/model_testing.py | head -n 1'
            }
        }
    }
}
