name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Проверка исходного кода
    - name: Checkout code
      uses: actions/checkout@v2

    # Установка Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Логин в Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Билд Docker-образа
    - name: Build Docker image
      run: |
        docker build -t streamlit_app:latest lab3/

    # Пуш образа в Docker Hub
    - name: Push Docker image to DockerHub
      run: |
        docker tag streamlit_app:latest ${{ secrets.DOCKER_USERNAME }}/streamlit_app:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/streamlit_app:latest
